### ISSUE TITLE
Not working from Webstorm

### ISSUE THREAD

**Issue by sherlock1982** [enobufs/mocha-prepare#3]
Hi! 
I'm trying to use it from a Webstorm and seems that a handler is not called.
I used your sample:

`
var prepare = require('mocha-prepare');

prepare(function (done) {
    // called before loading of test cases
    someAyncOp(function () {
        done();
    });
}, function (done) {
    // called after all test completes (regardless of errors)
    someAyncOp(function () {
        done();
    });
});
`
Here's my test/mochao.opts:

--timeout 60000 --require ./test/mocha.patch

Also Webstorm adds "--require ts-node/register" for typescript.

I see that the file is executed but callbacks are not launched.

I also tried directly "Mocha.prototype.run = ... " with no luck.

**Comment by enobufs** [comment]
I do not personally use WebStorm but many of my associates are using WebStrom along with mocha-prepare and I am sure it works with WebStorm.

One thing I am aware of is that if your WebStorm is configured to use globally installed mocha, the monkey patch mocha-prepare uses won't be effective. Please make sure your WebStorm's configuration to use the locally installed mocha module:

* Go to: `Run` -> `Run...` -> `Edit Configurations...`
* Make sure `Mocha package` is pointing to your local mocha package.

**Comment by sherlock1982** [comment]
Closing it, yes, you're right.

I had in Webstorm:

C:\webdriver-test\node_modules\mocha

While actually it was 

C:\Webdriver-test\node_modules\mocha

Seems case matters.

**Comment by enobufs** [comment]
wow...  I'm glad you found it. ;)
